### ISSUE TITLE
Update to newer versions of the `lsp` libraries

### ISSUE THREAD

**Issue by michaelpj** [agda/agda-language-server#26]
This is mostly annoying work, but I do make improvements to `lsp` and it would be nice if you were getting them.

(I do this work for HLS and I would like to do this for you if I get time, but I thought I would open this issue to track it anyway)

**Comment by banacorn** [comment]
Thank you for your work on `lsp`!

Just merged PR https://github.com/agda/agda-language-server/pull/23. 
Now the project builds with `lsp-2.7.0.0` and `lsp-types-2.3.0.0`.
